### ISSUE TITLE
请问怎么配置数据库呢？

### ISSUE THREAD

**Issue by womengnan** [QThans/layui-admin#17]
第四步：

先配置好数据库

$ php think migrate:run

提示：

 [InvalidArgumentException]
 There was a problem connecting to the database: SQLSTATE[HY000] [1045] Acce
 ss denied for user 'username'@'localhost' (using password: YES)

是在tp/config/database.php里面配置吗？

**Comment by QThans** [comment]
看文档。。。 .env 里面
