### ISSUE TITLE
阿里云oss上传失败

### ISSUE THREAD

**Issue by agentptx** [QThans/layui-admin#23]
阿里云oss上传失败，提示“Type is not supported”

**Comment by QThans** [comment]
tp版本，配置文件发下

**Comment by agentptx** [comment]
thinkphp6.0.2
filesystem.config
`
[FILESYSTEM]
 19 DRIVER=aliyun
`
`
 // 更多的磁盘配置信息
'aliyun' => [
    'type'         => 'aliyun',
    'accessId'     => 'id',
    'accessSecret' => 'secret',
    'bucket'       => 'buchet_name',
    'endpoint'     => 'oss-cn-hongkong.aliyuncs.com',
    'url'          => 'http://file.domain',//不要斜杠结尾，此处为URL地址域名。
],
`

**Comment by QThans** [comment]
你好 ，解决了吗？

**Comment by agentptx** [comment]
是的，已解决，不是配置文件的问题
