### ISSUE TITLE
开启多图片上传问题

### ISSUE THREAD

**Issue by agentptx** [QThans/layui-admin#24]
开启多图片上传问题，图片上传成功了，但是保存的时间只存了一张图片，还需要特别的设置吗？

**Comment by eaglepie** [comment]
大哥，你下载他这个到tp6里，怎么放的啊，有目录结构么，能公布一下么，谢谢了。我还没搭起来呢。

**Comment by agentptx** [comment]
直接使用composer安装，项目在vender里面

**Comment by eaglepie** [comment]
> 直接使用composer安装，项目在vender里面

嗯，我已经装好了，之前是安装的那个composer有问题，谢谢。
